-- Generated by Matugen - Color scheme configuration
-- This file is auto-generated but can be manually edited

require('base16-colorscheme').setup({
    base00 = "#141313",
    base01 = "#0e0e0d",
    base02 = "#1c1b1b",
    base03 = "#474740",
    base04 = "#c8c7be",
    base05 = "#e5e2e0",
    base06 = "#31302f",
    base07 = "#3a3938",

    base08 = "#b5bcb7",
    base09 = "#c2c8c4",
    base0A = "#c8c6c1",
    base0B = "#c7c7bc",
    base0C = "#3f4542",
    base0D = "#43443c",
    base0E = "#474743",
    base0F = "#b0ada6",
})

-- ============================================================================
-- Highlight Group Customization
-- ============================================================================
-- Override default base16 colors that don't contrast well

-- Helper function to set multiple highlight groups at once
local function set_hl_multiple(groups, value)
    for _, v in pairs(groups) do
        vim.api.nvim_set_hl(0, v, value)
    end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
    bg = '#43443c',
    fg = '#dcdbd0',  -- normal text contrast
})

-- Make "string" text contrast better
set_hl_multiple({ 'String', 'TSString' }, {
    fg = '#9aa49d',
})

-- Grey out comments with italic styling
set_hl_multiple({ 'TSComment', 'Comment' }, {
    fg = '#919189',
    italic = true,
})

-- Customize method highlighting
set_hl_multiple({ 'TSMethod', 'Method' }, {
    fg = '#c2c8c4',
})

-- Customize function highlighting
set_hl_multiple({ 'TSFunction', 'Function' }, {
    fg = '#c8c6c1',
})

-- Customize keyword highlighting
set_hl_multiple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
    fg = '#5e5f56',
})
